# Generated by Django 3.1.1 on 2020-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=150)),
                ('bid', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, height_field='30px', upload_to='', width_field='20px')),
            ],
        ),
    ]
