# Generated by Django 3.1.1 on 2020-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
