# Generated by Django 3.1.1 on 2020-10-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenttitle', to='auctions.auctionlist')),
            ],
        ),
    ]
