# Generated by Django 3.1.1 on 2020-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
