# Generated by Django 3.1.1 on 2020-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
